import 'katex/dist/katex.min.css';
import katex from 'katex';
function render_latex(latex: string, button: string) {
    const button_to_render = document.getElementById(button) as HTMLButtonElement;
    katex.render(latex, button_to_render, {
            throwOnError: false,
    });
};
render_latex('\\frac{a}{b}', "fraction_button");
render_latex(`{a}^{n}`, "superscript_button")
render_latex(`{a}_{m}`, "subscript_button")
render_latex(`{a}^{n}_{m}`, "sub_and_super_script_button")
render_latex(`{}^{n}a`, "left_superscript_button")
render_latex(`{}_{m}{a}`, "left_subscript_button")
render_latex(`{}^{n}_{m}{a}`, "left_sub_and_super_script_button")
render_latex(`\\sqrt{a}`, "root_button")
render_latex(`\\sqrt[2]{a}`, "root_2_button")
render_latex(`\\sqrt[3]{a}`, "root_3_button")
render_latex(`\\sqrt[n]{a}`, "root_universal_button")
render_latex(`\\int{}`, "undefined_integral_button")
render_latex(`\\int^a_b{}`, "defined_integral_button")
render_latex(`\\iint{}`, "undefined_double_integral_button")
render_latex(`\\iiint{}`, "undefined_triple_integral_button")
render_latex(`\\oint{}`, "undefined_surface_integral_button")
render_latex(`\\oint^a_b{}`, "defined_surface_integral_button")
render_latex(`\\oiint{}`, "undefined_double_surface_integral_button")
render_latex( `\\frac{d\\Box}{dx}`, "d_dx_button")
render_latex(`\\frac{d\\Box}{d\\Box}`, "d_d_button")
render_latex(`\\frac{dy}{dx}`, "dy_dx_button")
render_latex(`\\frac{d^{2}\\Box}{dx^{2}}`, "d2_dx2_button")
render_latex(`\\frac{d^{2}\\Box}{d\\Box^{2}}`, "d2_d2_button")
render_latex(`\\frac{d^{2}y}{dx^{2}}`, "d2y_dx2_button")
render_latex(`sin{}()`, "sin_button")
render_latex(`cos{}()`, "cos_button")
render_latex(`tan{}()`, "tan_button")
render_latex(`cot{}()`, "cot_button")
render_latex(`sec{}()`, "sec_button")
render_latex(`csc{}()`, "csc_button")
render_latex(`sin^{-1}{}()`, "arcsin_button")
render_latex(`cos^{-1}{}()`, "arccos_button")
render_latex(`tan^{-1}{}()`, "arctan_button")
render_latex(`cot^{-1}{}()`, "arccot_button")
render_latex(`sec^{-1}{}()`, "arcsec_button")
render_latex(`csc^{-1}{}()`, "arccsc_button")
render_latex(`(\\Box)`, "brackets_circle_button")
render_latex(`|\\Box|`, "brackets_module_button")
render_latex(`\\{ \\Box \\}`, "brackets_figure_button")
render_latex(`[\\Box]`, "brackets_square_button")
render_latex(`\\langle \\Box \\rangle`, "brackets_angle_button")
render_latex(`<`, "less_button")
render_latex(`>`, "more_button")
render_latex(`=`, "equal_button")
render_latex(`\\leq`, "less_equal_button")
render_latex(`\\geq`, "more_equal_button")
render_latex(`\\neq`, "not_equal_button")
render_latex(`\\rightarrow`, "right_arrow_button")
render_latex(`\\leftarrow`, "left_arrow_button")
render_latex(`\\leftrightarrow`, "double_arrow_button")
